# Generated by Django 5.2.17 on 2026-10-05 01:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0004_courseversion_published_at_alter_chapter_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.resourceversion')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('amount_sats', models.PositiveIntegerField()),
                ('inventory', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('expired', 'Vencida'), ('failed', 'No completada')], default='pending', max_length=12)),
                ('issue_state', models.CharField(choices=[('new', 'Sin emitir'), ('requested', 'Emisión solicitada'), ('ready', 'Emitida'), ('unknown', 'Por conciliar')], default='new', max_length=12)),
                ('payment_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('payment_request', models.TextField(blank=True)),
                ('incident', models.CharField(blank=True, max_length=40)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CommerceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='commerce.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='nombre de la oferta')),
                ('amount_sats', models.PositiveIntegerField(verbose_name='precio en sats de prueba')),
                ('kind', models.CharField(choices=[('course', 'Curso o tutorial'), ('chapter', 'Capítulo'), ('lesson', 'Texto de lección'), ('resource', 'Video o material')], max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'En revisión'), ('active', 'Disponible'), ('archived', 'Retirada')], default='draft', max_length=12)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.versionchapter')),
                ('course_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.courseversion')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.versionlesson')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.resourceversion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.offer'),
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='commerce.offer')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.resourceversion')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_hash', models.CharField(max_length=64, unique=True)),
                ('amount_msat', models.BigIntegerField()),
                ('observed_at', models.DateTimeField()),
                ('resolution', models.CharField(max_length=40)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='commerce.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase', to='commerce.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntitlementSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.entitlement')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.purchase')),
            ],
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(fields=('buyer', 'resource'), name='unique_buyer_resource_right'),
        ),
        migrations.AddConstraint(
            model_name='commerceevent',
            constraint=models.UniqueConstraint(fields=('invoice', 'kind'), name='unique_invoice_event'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('amount_sats__gte', 1), ('amount_sats__lte', 100000)), name='offer_positive_simulated_price'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('buyer', 'offer'), name='one_pending_invoice_per_offer'),
        ),
        migrations.AddConstraint(
            model_name='offeritem',
            constraint=models.UniqueConstraint(fields=('offer', 'resource'), name='unique_offer_resource'),
        ),
        migrations.AddConstraint(
            model_name='entitlementsource',
            constraint=models.UniqueConstraint(fields=('entitlement', 'purchase'), name='unique_right_purchase_source'),
        ),
    ]
