# Generated by Django 5.2.17 on 2026-10-05 01:58

from django.conf import settings
from django.db import migrations, models


def assign_logical_keys(apps, schema_editor):
    Offer = apps.get_model('commerce', 'Offer')
    Invoice = apps.get_model('commerce', 'Invoice')
    for offer in Offer.objects.all():
        field = 'course_version_id' if offer.kind == 'course' else offer.kind + '_id'
        logical_key = f'{offer.kind}:{getattr(offer, field)}'
        Offer.objects.filter(pk=offer.pk).update(logical_key=logical_key)
        Invoice.objects.filter(offer_id=offer.pk).update(logical_key=logical_key)


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('content', '0004_courseversion_published_at_alter_chapter_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='one_pending_invoice_per_offer',
        ),
        migrations.AddField(
            model_name='invoice',
            name='logical_key',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='offer',
            name='logical_key',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
        migrations.RunPython(assign_logical_keys, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('buyer', 'logical_key'), name='one_pending_invoice_per_offer'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('logical_key',), name='one_active_offer_per_target'),
        ),
    ]
