# Generated by Django 5.2.17 on 2026-10-03 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import media.models
import media.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=media.storage.PrivateStorage(), upload_to=media.models.private_name, verbose_name='archivo privado')),
                ('original_name', models.CharField(editable=False, max_length=200)),
                ('kind', models.CharField(editable=False, max_length=12)),
                ('mime_type', models.CharField(editable=False, max_length=80)),
                ('size', models.PositiveBigIntegerField(editable=False)),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='propietario')),
            ],
            options={
                'verbose_name': 'archivo privado',
                'verbose_name_plural': 'archivos privados',
            },
        ),
    ]
