# Generated by Django 5.2.17 on 2026-10-03 02:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='identificador')),
            ],
            options={
                'verbose_name': 'tema',
                'verbose_name_plural': 'temas',
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='duración estimada en minutos'),
        ),
        migrations.AddField(
            model_name='course',
            name='kind',
            field=models.CharField(choices=[('course', 'Curso'), ('tutorial', 'Tutorial')], default='course', max_length=12, verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], max_length=12, verbose_name='nivel'),
        ),
        migrations.CreateModel(
            name='ExternalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=12, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('source_name', models.CharField(max_length=160, verbose_name='fuente')),
                ('source_url', models.URLField(max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='enlace a la fuente')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.topic', verbose_name='tema')),
            ],
            options={
                'verbose_name': 'referencia externa',
                'verbose_name_plural': 'referencias externas',
                'ordering': ('title', 'pk'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.topic', verbose_name='tema'),
        ),
        migrations.AddField(
            model_name='material',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.topic', verbose_name='tema'),
        ),
        migrations.AddField(
            model_name='video',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.topic', verbose_name='tema'),
        ),
    ]
