# Generated by Django 5.2.17 on 2026-10-03 03:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_resource_keys(apps, schema_editor):
    for name in ("Lesson", "Video", "Material"):
        model = apps.get_model("content", name)
        for pk in model.objects.using(schema_editor.connection.alias).values_list("pk", flat=True).iterator():
            model.objects.using(schema_editor.connection.alias).filter(pk=pk).update(resource_key=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_topic_course_estimated_minutes_course_kind_and_more'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='resource_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='pending_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.asset', verbose_name='archivo de la próxima revisión'),
        ),
        migrations.AddField(
            model_name='material',
            name='pending_subtitles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.asset', verbose_name='subtítulos VTT de la próxima revisión'),
        ),
        migrations.AddField(
            model_name='material',
            name='resource_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='transcript',
            field=models.TextField(blank=True, verbose_name='transcripción'),
        ),
        migrations.AddField(
            model_name='video',
            name='pending_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.asset', verbose_name='archivo de la próxima revisión'),
        ),
        migrations.AddField(
            model_name='video',
            name='pending_subtitles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.asset', verbose_name='subtítulos VTT de la próxima revisión'),
        ),
        migrations.AddField(
            model_name='video',
            name='resource_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='transcript',
            field=models.TextField(blank=True, verbose_name='transcripción'),
        ),
        migrations.CreateModel(
            name='CourseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('course', 'Curso'), ('tutorial', 'Tutorial')], max_length=12)),
                ('level', models.CharField(blank=True, choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], max_length=12)),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('creator_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sealed', models.BooleanField(default=False, editable=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='content.course')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.topic')),
            ],
            options={
                'verbose_name': 'versión publicada',
                'verbose_name_plural': 'versiones publicadas',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='current_version',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.courseversion'),
        ),
        migrations.CreateModel(
            name='ResourceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_key', models.UUIDField(default=uuid.uuid4)),
                ('number', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('text', 'Texto'), ('video', 'Video'), ('material', 'Material')], max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('access_type', models.CharField(choices=[('free', 'Gratis'), ('paid', 'De pago')], max_length=8)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.asset')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('subtitles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.asset')),
            ],
            options={
                'verbose_name': 'revisión de recurso',
                'verbose_name_plural': 'revisiones de recursos',
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='content.lesson')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.resourceversion', verbose_name='revisión de recurso')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='material',
            name='revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.resourceversion'),
        ),
        migrations.AddField(
            model_name='video',
            name='revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.resourceversion'),
        ),
        migrations.CreateModel(
            name='VersionChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField()),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='content.courseversion')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='VersionLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_lesson_id', models.PositiveBigIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='content.versionchapter')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.resourceversion')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='VersionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.resourceversion')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='content.versionlesson')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='courseversion',
            constraint=models.UniqueConstraint(fields=('course', 'number'), name='unique_course_version'),
        ),
        migrations.AddConstraint(
            model_name='resourceversion',
            constraint=models.UniqueConstraint(fields=('resource_key', 'number'), name='unique_resource_revision'),
        ),
        migrations.AddConstraint(
            model_name='lessonresource',
            constraint=models.UniqueConstraint(fields=('lesson', 'position'), name='unique_lesson_attachment_position'),
        ),
        migrations.AddConstraint(
            model_name='versionchapter',
            constraint=models.UniqueConstraint(fields=('version', 'position'), name='unique_version_chapter_position'),
        ),
        migrations.AddConstraint(
            model_name='versionlesson',
            constraint=models.UniqueConstraint(fields=('chapter', 'position'), name='unique_version_lesson_position'),
        ),
        migrations.AddConstraint(
            model_name='versionattachment',
            constraint=models.UniqueConstraint(fields=('lesson', 'position'), name='unique_version_attachment_position'),
        ),
        migrations.RunPython(assign_resource_keys, migrations.RunPython.noop),
        migrations.AlterField(model_name="lesson", name="resource_key", field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
        migrations.AlterField(model_name="video", name="resource_key", field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
        migrations.AlterField(model_name="material", name="resource_key", field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
    ]
