# Generated by Django 5.2.17 on 2026-10-05 01:50

from django.db import migrations, models
from django.utils import timezone


def mark_published(apps, schema_editor):
    Course = apps.get_model('content', 'Course')
    Version = apps.get_model('content', 'CourseVersion')
    Submission = apps.get_model('creators', 'Submission')
    ids = set(Course.objects.exclude(current_version=None).values_list('current_version_id', flat=True))
    ids.update(Submission.objects.filter(status='approved').exclude(course_version=None).values_list('course_version_id', flat=True))
    Version.objects.filter(pk__in=ids, sealed=True).update(published_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_lesson_resource_key_material_pending_asset_and_more'),
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseversion',
            name='published_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(mark_published, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='chapter',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Retirado del catálogo')], default='draft', max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Retirado del catálogo')], default='draft', max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='externalreference',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Retirado del catálogo')], default='draft', max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Retirado del catálogo')], default='draft', max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Retirado del catálogo')], default='draft', max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Retirado del catálogo')], default='draft', max_length=12, verbose_name='estado'),
        ),
    ]
