# Generated by Django 5.2.17 on 2026-10-04 05:01

import django.db.models.functions.text
from django.db import migrations, models


def separate_existing_accounts(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Profile = apps.get_model('creators', 'CreatorProfile')
    creator_ids = set(Profile.objects.values_list('user_id', flat=True))
    for model_name in ('Course', 'Video', 'Material'):
        creator_ids.update(apps.get_model('content', model_name).objects.values_list('creator_id', flat=True))
    User.objects.filter(pk__in=creator_ids, is_staff=False, is_superuser=False).update(account_type='creator')
    User.objects.filter(models.Q(is_staff=True) | models.Q(is_superuser=True)).update(account_type='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email_case_insensitive',
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('student', 'Estudiante'), ('creator', 'Creador'), ('admin', 'Administración')], default='student', max_length=12, verbose_name='tipo de cuenta'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='correo'),
        ),
        migrations.RunPython(separate_existing_accounts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('account_type'), name='unique_email_per_account_type'),
        ),
    ]
