# Generated by Django 5.2.17 on 2026-10-10 15:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0002_remove_invoice_one_pending_invoice_per_offer_and_more'),
        ('content', '0004_courseversion_published_at_alter_chapter_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('kind', models.CharField(db_index=True, max_length=40)),
                ('session_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_events', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commerce.invoice')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commerce.offer')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.resourceversion')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.courseversion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
