# Generated by Django 5.2.17 on 2026-10-05 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_courseversion_published_at_alter_chapter_status_and_more'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.versionlesson'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completed_lessons', to='learning.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.versionlesson')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'lesson'), name='unique_completed_enrollment_lesson')],
            },
        ),
    ]
