# Generated by Django 5.2.17 on 2026-10-08 00:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_courseversion_published_at_alter_chapter_status_and_more'),
        ('learning', '0002_enrollment_last_lesson_enrollment_revision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('pass_mark', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='nota mínima')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='intentos permitidos')),
                ('wait_minutes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10080)], verbose_name='espera entre intentos (minutos)')),
                ('required', models.BooleanField(default=True, verbose_name='Exigir aprobación para completar la lección')),
                ('feedback', models.CharField(choices=[('submitted', 'Al entregar cada intento'), ('passed', 'Solo al aprobar')], default='submitted', max_length=12, verbose_name='mostrar soluciones')),
                ('questions', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True, verbose_name='Incluir evaluación en la próxima versión')),
                ('revision', models.PositiveIntegerField(default=0)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_draft', to='content.lesson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VersionQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('pass_mark', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='nota mínima')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='intentos permitidos')),
                ('wait_minutes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10080)], verbose_name='espera entre intentos (minutos)')),
                ('required', models.BooleanField(default=True, verbose_name='Exigir aprobación para completar la lección')),
                ('feedback', models.CharField(choices=[('submitted', 'Al entregar cada intento'), ('passed', 'Solo al aprobar')], default='submitted', max_length=12, verbose_name='mostrar soluciones')),
                ('questions', models.JSONField(blank=True, default=list)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='quiz', to='content.versionlesson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('correct_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_attempts', to='learning.enrollment')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='learning.versionquiz')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'quiz', 'number'), name='unique_quiz_attempt_number'), models.UniqueConstraint(condition=models.Q(('submitted_at__isnull', True)), fields=('enrollment', 'quiz'), name='one_open_quiz_attempt')],
            },
        ),
        migrations.CreateModel(
            name='ExtraQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowance_before', models.PositiveIntegerField()),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learning.enrollment')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learning.versionquiz')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'quiz', 'allowance_before'), name='unique_extra_quiz_allowance')],
            },
        ),
    ]
