# Generated by Django 5.2.17 on 2026-10-10 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_courseversion_published_at_alter_chapter_status_and_more'),
        ('learning', '0005_certificate_fingerprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('request_key', models.UUIDField()),
                ('hidden', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='learning.communitypost')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.courseversion')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'permissions': [('moderate_community', 'Moderar comunidades de todos los cursos')],
            },
        ),
        migrations.CreateModel(
            name='CommunityDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('hide', 'Ocultar'), ('show', 'Mostrar'), ('close', 'Cerrar'), ('open', 'Reabrir'), ('dismiss', 'Descartar reportes'), ('suspend', 'Suspender escritura'), ('restore', 'Restablecer escritura')], max_length=12)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='community_decisions', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.courseversion')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='learning.communitypost')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='learning.communitypost')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunitySuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.courseversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='communitypost',
            constraint=models.UniqueConstraint(fields=('author', 'request_key'), name='unique_community_post_request'),
        ),
        migrations.AddConstraint(
            model_name='communityreport',
            constraint=models.UniqueConstraint(fields=('post', 'reporter'), name='unique_community_report'),
        ),
        migrations.AddConstraint(
            model_name='communitysuspension',
            constraint=models.UniqueConstraint(fields=('version', 'student'), name='unique_community_suspension'),
        ),
    ]
