# Generated by Django 5.2.17 on 2026-10-04 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0003_lesson_resource_key_material_pending_asset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=160, verbose_name='nombre público')),
                ('bio', models.TextField(verbose_name='biografía')),
                ('specialty', models.CharField(max_length=200, verbose_name='especialidad')),
                ('website', models.URLField(blank=True, verbose_name='sitio web')),
                ('status', models.CharField(choices=[('pending', 'Solicitud pendiente'), ('approved', 'Aprobado'), ('changes', 'Cambios solicitados'), ('suspended', 'Suspendido')], default='pending', max_length=12)),
                ('feedback', models.TextField(blank=True, verbose_name='observaciones')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator_approvals', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='creator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En revisión'), ('approved', 'Publicado'), ('changes', 'Cambios solicitados'), ('withdrawn', 'Retirado por el creador')], default='pending', max_length=12)),
                ('feedback', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.course')),
                ('course_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.courseversion')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.material')),
                ('resource_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.resourceversion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_reviews', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.video')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('course_version__isnull', False), ('material__isnull', True), ('resource_version__isnull', True), ('video__isnull', True)), models.Q(('course__isnull', True), ('course_version__isnull', True), ('material__isnull', True), ('resource_version__isnull', False), ('video__isnull', False)), models.Q(('course__isnull', True), ('course_version__isnull', True), ('material__isnull', False), ('resource_version__isnull', False), ('video__isnull', True)), _connector='OR'), name='submission_exactly_one_content'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('course',), name='one_pending_course'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('video',), name='one_pending_video'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('material',), name='one_pending_material')],
            },
        ),
    ]
